package com.group_finity.mascot.imagesetchooser;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import javax.imageio.ImageIO;
import javax.swing.*;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 * Displays information about an image set. Used by {@link ImageSetChooser}.
 */
public class ImageSetChooserPanel extends JPanel {
    String imageSet;

    public ImageSetChooserPanel() {
        initComponents();
    }

    public ImageSetChooserPanel(String imageSet, String actions,
                                String behaviors, Path imageLocation, String caption) {
        initComponents();

        this.imageSet = imageSet;
        this.caption.setText(caption); // 标题
        this.caption.setFont(this.caption.getFont().deriveFont(Font.BOLD)); // 字体
        actionsFile.setText(actions); // 动作文件使用标签展示
        behaviorsFile.setText(behaviors); // 行为文件使用标签展示
        try { // 加载图片后也用标签展示
            BufferedImage img = ImageIO.read(Files.newInputStream(imageLocation));
            image.setIcon(new ImageIcon(img.getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
        } catch (IOException e) {
            // Doesn't matter, the image just won't show
        }
    }

    public void setCheckbox(boolean value) {
        checkbox.setSelected(value);
    }

    public String getImageSetName() {
        return imageSet;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox = new JCheckBox();
        caption = new JLabel();
        actionsFile = new JLabel();
        behaviorsFile = new JLabel();
        image = new JLabel();

        setOpaque(false); // 不透明
        setMinimumSize(new Dimension(248, 80));
        setPreferredSize(new Dimension(248, 80));
        setLayout(new AbsoluteLayout()); // 布局管理器

        checkbox.setOpaque(false);
        add(checkbox, new AbsoluteConstraints(10, 30, -1, -1));

        caption.setText("Builder");
        add(caption, new AbsoluteConstraints(110, 10, -1, -1));

        actionsFile.setText("img/Builder/conf/actions.xml");
        add(actionsFile, new AbsoluteConstraints(110, 30, -1, -1));

        behaviorsFile.setText("img/Builder/conf/behaviors.xml");
        add(behaviorsFile, new AbsoluteConstraints(110, 50, -1, -1));

        image.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0))); // 图片加上边框
        add(image, new AbsoluteConstraints(40, 10, 60, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**动作文件标签 */
    private JLabel actionsFile;
    /**行为文件名称-标签 */
    private JLabel behaviorsFile;
    /**标题-标签 */
    private JLabel caption;
    /**单选框 */
    private JCheckBox checkbox;
    /**图片-标签 */
    private JLabel image;
    // End of variables declaration//GEN-END:variables
}
